name: Build cross
on:
  push:

jobs:
  nightly:
    name: Deploy releases
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        foo: [bar]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ldc-latest

      - id: foo
        run: |
          echo "${{matrix.foo}}" >> $GITHUB_OUTPUT

      - id: bar
        run: |
          if [ -z "${{matrix.bar}}" ]; then
            echo "${{matrix.bar}}" >> $GITHUB_OUTPUT
          else
            echo "${{matrix.foo}}" >> $GITHUB_OUTPUT
          fi

      - name: print foo
        run: echo "${{ steps.foo.outputs.* }}"

      - name: print bar
        run: echo "${{ steps.foo.outputs.* }}"

      - name: print bar
        run: echo $BAR

      - name: Build executable
        run: dub build --arch=arm64-apple-macos --build=release

      - name: Compress executable
        run: tar -cvzf test-aarch64-osx.tar.gz m1-cross-test

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-build-osx
          path: test-aarch64-osx.tar.gz
