name: Build cross
on:
  push:

jobs:
  nightly:
    name: Deploy releases
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        foo: [bar]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ldc-latest

      - name: set env
        run:
          export FOO=${{matrix.foo}}
          export BAR=${{matrix.bar}}

          if [ -z "$BAR" ]; then
            export BAR="$FOO"
          fi

      - name: print foo
        run: echo $FOO

      - name: print bar
        run: echo $BAR

      - name: Build executable
        run: ./ldc2-1.30.0-osx-universal/bin/dub build --arch=arm64-apple-macos --build=release

      - name: Compress executable
        run: tar -cvzf test-aarch64-osx.tar.gz m1-cross-test

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: aarch64-build-osx
          path: test-aarch64-osx.tar.gz
